<?php

declare(strict_types=1);

/*
 * Local Fonts
 *
 * Package: vtinnovations/localfonts
 * Copyright: V&T Innovations
 * Licence: LGPL-3.0-or-later
 * Website: https://www.v-t.one
 */

namespace VTinnovations\LocalFonts\Service;

final class CssGenerator
{
    public function __construct(
        private readonly FontStorage $storage,
        private readonly string $projectDir,
        private readonly ContaoFileRegistry $fileRegistry,
    ) {
    }

    /**
     * @param array<string,array{family:string, variants:list<string>, files:list<array{url:string, weight:string, style:string, unicodeRange:string}>}> $fonts
     */
    public function generate(array $fonts, string $fontDisplay = 'swap'): void
    {
        $dir = $this->storage->getPublicDir();

        if (!is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        // Marker + symlink into the web root, otherwise /files/localfonts/… 404s.
        $this->storage->makeWebAccessible();

        $css = "/* Generated by Local Fonts. */\n";

        foreach ($fonts as $key => $font) {
            foreach ($font['files'] as $file) {
                $extension = pathinfo(parse_url($file['url'], PHP_URL_PATH) ?: '', PATHINFO_EXTENSION) ?: 'woff2';
                $filename = $key . '-' . $file['style'] . '-' . $file['weight'] . '-' . substr(sha1($file['url']), 0, 8) . '.' . $extension;
                $format = 'woff2' === $extension ? 'woff2' : $extension;

                $css .= "\n@font-face {\n";
                $css .= "  font-family: '" . str_replace("'", "\\'", $font['family']) . "';\n";
                $css .= "  src: url('/files/localfonts/" . $key . '/' . $filename . "') format('" . $format . "');\n";
                $css .= "  font-style: " . $file['style'] . ";\n";
                $css .= "  font-weight: " . $file['weight'] . ";\n";
                $css .= "  font-display: " . $fontDisplay . ";\n";

                if ('' !== ($file['unicodeRange'] ?? '')) {
                    $css .= "  unicode-range: " . $file['unicodeRange'] . ";\n";
                }

                $css .= "}\n";
            }
        }

        $target = $dir . '/localfonts.css';

        file_put_contents($target, $css);
        $this->fileRegistry->registerPublicPath($dir, $this->projectDir);
        $this->fileRegistry->registerPublicPath($target, $this->projectDir);
    }
}
